name: Build Boost Headers

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays at 00:00 UTC

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Download latest boost
      run: |
        wget -O boost.tar.gz https://archives.boost.io/release/1.86.0/source/boost_1_86_0.tar.gz
        tar -xzf boost.tar.gz

    - name: Apply patch from commit https://github.com/boostorg/qvm/commit/106d411db30d44966d2db5397508d01ce170e17d
      run: |
        wget -O new_quat_traits.hpp https://raw.githubusercontent.com/boostorg/qvm/develop/include/boost/qvm/quat_traits.hpp
        cp new_quat_traits.hpp boost_1_86_0/boost/qvm/quat_traits.hpp
        rm new_quat_traits.hpp

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f boost_1_86_0
        git commit -m "Update Boost headers" || echo "No changes to commit"
        git push